{% set name = "shadie" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/elissasoroj/shadie/archive/{{ version }}.tar.gz
  sha256: cd66043a809c649c935e1c42d8da1ad3451ca95cc5d47aedb8307c88e3092ff7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - slim >=4.2
    - toytree >=3.0.1
    - altair
    - msprime
    - tskit
    - pyslim

test:
  imports:
    - shadie

about:
  home: https://github.com/elissasoroj/shadie
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: SLiM simulations in Python.
  description: |
    A library for simulating evolution using SLiM, implementing
    a hybrid approach with msprime and analyzing output.
  doc_url: https://elissasoroj.github.io/shadie
  dev_url: https://github.com/elissasoroj/shadie

extra:
  recipe-maintainers:
    - elissasoroj
    - eaton-lab
