{% set name = "shadie" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/elissasoroj/shadie/archive/{{ version }}.tar.gz
  # sha256: 007295e2541ba5d86baa0af0c9397d4064341011a6bec72a8d12aafb4da34825
  url: https://github.com/eaton-lab/shadie/archive/{{ version }}.tar.gz
  sha256: bc15a4dbdef08cc5a179f55715a8e63f94edf38ef6d72578374ff12fddeff182

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - slim >=4.2
    - toytree >=3.0.1
    - altair
    - msprime
    - tskit
    - pyslim

test:
  imports:
    - shadie

about:
  home: https://github.com/elissasoroj/shadie
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: SLiM simulations in Python.
  description: |
    A library for simulating evolution using SLiM, implementing
    a hybrid approach with msprime and analyzing output.
  doc_url: https://elissasoroj.github.io/shadie
  dev_url: https://github.com/elissasoroj/shadie

extra:
  recipe-maintainers:
    - elissasoroj
    - eaton-lab
